# ### 
GET http://127.0.0.1:9999/v1/download?id=9e711dd8-e83c-4809-bcd0-05b377c432ad&type=mesh

###
POST http://127.0.0.1:9999/v1/api/region/mesh 
content-type: application/json

{
    "type" : "polygon",
    "data" : [
        {"latitude" : -33.005, "longitude" : 151.0056},
        {"latitude" : -33.021, "longitude" : 151.078},
        {"latitude" : -33.037, "longitude" : 151.384}
    ]
}

###
POST http://127.0.0.1:9999/v1/api/region/mesh 
content-type: application/json

{
    "type" : "circle",
    "data" : {
        "latitude" : -34, 
        "longitude" :  148,
        "radius" : 3
    }
}
###
POST http://127.0.0.1:9999/v1/api/region/mesh 
content-type: application/json

{
    "type" : "circle",
    "data" : {
        "latitude" : -33.5, 
        "longitude" :  151.5,
        "radius" : 3
    }
}
###
POST http://127.0.0.1:9999/v1/api/region/mesh 
content-type: application/json

{
    "type" : "polygon",
    "data" : [
        {"latitude" : -33.005, "longitude" : 151.0056},
        {"latitude" : -33.01, "longitude" : 151.01}
    ]
}

###
DELETE  http://127.0.0.1:9999/v1/clear/regions
content-type: application/json

{
    "key": 539326398030126706
}